services:
  service-login:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: container-login
    ports:
      - "3000:3000"
    command: npm run localhost
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
      - action: sync
        path: ./src
        target: /app/src
      - action: rebuild
        path: package.json