services:
  bbom-auth-login-module-localhost:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: bbom-auth-login-module
    ports:
      - "3000:3000"
    command: npm run localhost
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
      - action: sync
        path: ./src
        target: /app/src
      - action: rebuild
        path: package.json

  bbom-auth-login-tests:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run test:isolated
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - test