export const BBOM_CLIENT_BAD_REQUEST = "BBOM-CLIENT-BAD-REQUEST";
export const BBOM_CONNECT_BURM_FAILED = "BBOM-CONNECT-BURM-FAILED";
export const BBOM_CONNECT_BURM_TIMEOUT = "BBOM-CONNECT-BURM-TIMEOUT";
export const BBOM_CONNECT_BURM_UNAUTHORIZED = "BBOM-CONNECT-BURM-UNAUTHORIZED";