export const BBOM_LOGIN_VALIDATIONS_FORMAT = "BBOM-LOGIN-VALIDATIONS-FORMAT";
export const BBOM_LOGIN_INTERNAL_SERVER_ERROR = "BBOM-LOGIN-INTERNAL-SERVER-ERROR";
export const BBOM_LOGIN_UNAUTHORIZED = "BBOM-LOGIN-UNAUTHORIZED";